name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: cd ./cpp/MPU_6050
    - name: make
      run: g++ main.cpp -o test -lwiringPi ./libSensor.cpp

